#!/bin/bash

# SmileCDR chokes on the examples in the IG package.tgz - gotta do a fixup
echo "Fixing ImplementationGuide in package.tgz..."
cd output
tar xzf package.tgz
cd package
jq 'del(.definition.resource[] | select(.exampleCanonical != null))' <ImplementationGuide-nz.central.ihub.ig.json > fixed.json
rm ImplementationGuide-nz.central.ihub.ig.json
mv fixed.json ImplementationGuide-nz.central.ihub.ig.json
cd ..
mv package.tgz package.orig.tgz
tar czf package.tgz package
rm -rf package
cd ..
echo "Fixed IG in package.tgz"

