CodeSystem:  NZCentralRegionReferralReasonCodeSystem
Id: nzcr-referral-reason-cs
Title: "NZ Central Region - Referral Reason Code System"
Description:  "Referral Reason codes; ex. WebPAS in NZ Central Region."

* ^url = $NZCentralRegionReferralReasonCS
* ^status = #active
* ^experimental = false
* ^caseSensitive = true

/*  These 'Referral Reasons' seem to be more applicable to Condition

* #AA "Axillary Abscess"
* #AAA "Abdominal aortic anuerysm"
* #ABC "Abnormal Cervix"
* #ABD "Abdominal distension"
* #ABDP "Abdominal Pain"
* #ABNCXR "Abnormal CXR"
* #ABNLUNGFX "Abnormal Lung Function"
* #ABNSPUTUM "Abnormal Sputum"
* #ABP "Abnormal bowel pattern"
* #ABS "Abscess"
* #AC "Audiology concern NEC"
* #ACD "Allergic Contacy Dermatitis"
* #ACE "Acne"
* #ACHA "Achalasia"
* #ACI "Acidosis"
* #ACP "Acute Poliomyelitis"
* #ACT "Actinic Keratosis"
* #ACY "Agc Cytology"
* #AD "Atopic Dermatitis"
* #ADBM "Abdominal mass"
* #ADD "Attention Deficit Disorder"
* #ADE "Adenoids"
* #ADEN "Adenocarcinoma"
* #ADSITU "Adenocarcinoma in-situ"
* #ADT "Adenoids & Tonsils"
* #AHC "Asc-H Cytology"
* #AHF "Acute Heart Failure"
* #AHL "Assymetrical Hearing Loss"
* #AIV "Acquired Immunodeficiency Virus"
* #AL "Pain in left ankle and joints of left fo"
* #ALA "Alcohol Abuse"
* #ALF "Allergies"
* #ALI "Allergies/Intolerances"
* #ALL "Allergies"
* #ALY "Acute lymphadenitis"
* #ALZ "Alzheimers Disease"
* #AMB "Amblyopia"
* #AME "Amelia"
* #AML "Acute Myelogenous Leukemia"
* #AMOL "Acute Monocytic Leukaemia"
* #AMP "Amputation"
* #AN "Anaemia"
* #ANA "Anaemia"
* #ANAL "Anal Fissure"
* #ANE "Anaemia"
* #ANF "Anti-Inflamm Injec 4 R.A."
* #ANG "Angina"
* #ANH "Antepartum Haemorrage"
* #ANK "Ankle Pain"
* #ANO "Anosmia"
* #ANTD "AntiD Rh Antibodies"
* #ANX "Anxiety"
* #AOM "Acute otitis media"
* #APH "Aphasia"
* #APL "Abdominal Pain Llq"
* #APML "Acute Promyelocytic Leukaemia"
* #APNOEA "Apnoea"
* #APR "Abdominal Pain Rlq"
* #ARR "Arrhythmias"
* #ART "Arthrogryposis"
* #ARTH "Arthritis"
* #ARTT "Arteritis"
* #ARYTHMIA "Arythmia"
* #ASD "Autistic Spectrum Disorder"
* #ASS "Assessment"
* #AST "Asthma"
* #Asthma "Asthma"
* #ASY "Ashermans Syndrome"
* #ATA "Ataxia"
* #ATB "Atrial Fib"
* #ATF "Atrial Fibrillation"
* #ATL "Achilles tendonitis, left leg"
* #ATR "Achilles tendonitis, right leg"
* #AUC "Asc-Us Cytology"
* #AUL "Amputation of Upper Limb"
* #AULCR "Autoimmune Ulcer"
* #AUP "Aural Polyp"
* #AURE "Acute urinary retention"
* #AUT "Autisitic Disorder"
* #BA "Bariatric"
* #BAR "Bariatric"
* #BC "Breast Cancer"
* #BCA "Breast Cancer"
* #BCAN "Breast Cancer"
* #BCC "Basal Cell Carcinoma"
* #BCG "Basal Cell Cancer Gum"
* #BCK "Back Pain"
* #BCL "B Cell Lymphoma"
* #BCM "Basal Cell Cancer Mouth"
* #BCU "Bicornate Uterus"
* #BDO "Bleeding Disorders"
* #BEN "Benign"
* #BFM "Bulky Floor Of Mouth"
* #BHL "Bunion,Hallux valgus,acquired, left foot"
* #BHR "Bunion,Hallux valgus,acquired,right foot"
* #BKPN "Back Pain"
* #BLA "Bladder"
* #BLAC "Bladder Cancer"
* #BLB "Benign Lesion of Bone"
* #BLC "Breast Left Cancer"
* #BLI "Blindness/and/or Vision Impairment"
* #BLL "Benign Lesion of Lip"
* #BLM "Benign Lesion of Mouth"
* #BM "Bladder Metastatic"
* #BMC "Breast Metastatic Cancer"
* #BMET "Bone Metastatic"
* #BP "Blood Pressure"
* #BPEM "Bullous Pemphigoid"
* #BPR "Breast Primary"
* #BRA "Bradycardia"
* #BRC "Breast Right Cancer"
* #BRE "Breast cancer"
* #BRI "Brain Injury"
* #BRM "Brain Metastatic"
* #BRONCHTS "Bronchiectasis"
* #BRR "Breast Reconstruction"
* #BT "Blood Transfusion"
* #BTR "Blood Transfusion"
* #BUN "Bunion"
* #BUR "Burns"
* #BURN "Burn"
* #BVI "Bacterial/Viral Infections"
* #C1 "Cin 1 Biopsy"
* #C2 "Cin 2 Biopsy"
* #C3B "Cin 3 Biopsy Endocervix"
* #C3E "Cin 3 Exocervix"
* #C3O "Cin 3 Other Parts Of Cervix"
* #CA0 "Conjunctivitis"
* #CA1 "Pterygium"
* #CA2 "Other conjunctival anomaly"
* #CAD "Coronary Artery Disease"
* #CAE "Coeliac"
* #CAF "Contracture of ankle and foot joint"
* #CAL "Cancer Laryngeal"
* #CALL "Callous"
* #CALUNG "CA Lung"
* #CAN "Cancer"
* #CAO "Cancer Oropharynx"
* #CAP "Cancer Pharyngeal"
* #CAR "Cardiomyopathy"
* #CART "Carcinoid Tumour"
* #CAT "Cataract"
* #CATH "Cancer Throat"
* #CATO "Cancer Tongue"
* #CAU02 "Febrile convulsion"
* #CAY "Cardiomyopathy"
* #CB "Cancer Bladder"
* #CCAN "Colon Cancer"
* #CCD "Cognitive Communication Disorder"
* #CCN "Cervical Cancer Nos"
* #CCO "Congenital coxa vara"
* #CCV "Congenital Coxa valga"
* #CDD "Chronic renal disease"
* #CDH "Congntl deformities hip,acetabular dyspl"
* #CEA "Cerebrovascular Accident"
* #CECAN "Cervical Cancer"
* #CED "Cerebrovascular Disease"
* #CEL "Cellulitis"
* #CELL "Cellulitis"
* #CEM "Cytologic Evidence Og Malignancy"
* #CEN "Cancer Neck"
* #CEP "Cerebral Palsy"
* #CER "Cervicitis/Endocervicitis"
* #CF "Club Foot"
* #CFH "Colon Cancer Family History"
* #CFI "Cystic Fibrosis"
* #CFS "Chronic Fatigue Syndrome"
* #CH "Clicky Hips"
* #CHAIT "Chait Tube Fu"
* #CHAITR "Chait Tube Removal"
* #CHD "Congenital hearing disorder"
* #CHESTPAIN "Chest Pain/Angina"
* #CHF "Congestive Heart Failure"
* #CHFEO "CHF exacerbated oedema"
* #CHL "Congential Hearing loss"
* #CHO "Choledocholithiasis"
* #CHOL "Cholelithiasis"
* #CHR "Crohns"
* #CIC "Cervical Polyp"
* #CK "Cancer Kidney"
* #CKD "Chronic Kidney Disease"
* #CLA "Contracture, left ankle"
* #CLK "Contracture, left knee"
* #CLL "Chronic Lymphocytic Leukaemia"
* #CLN "Cancer Lymph Node"
* #CLP "Cleft Palate"
* #CLS "Cyst / Lesion Scalp"
* #CLT "Clinical Trial"
* #CME "Chronic Middle Effusion"
* #CML "Chronic Myeloid Leukemia"
* #CNC "Cancer Nasal"
* #CNJ "Contracture of knee joint"
* #CNS "CNS Lymphoma"
* #CO0 "Megalocornea"
* #CO1 "Keratitis"
* #CO3 "Keratoconus"
* #COA "Cancer Of Adenoids"
* #COCC "Combined Oral Contraception"
* #COD "Congenital Diplegia"
* #COE "Coeliac Disease"
* #COF "Cancer Of Fundis Uteri"
* #COG "Cognitive impairment"
* #COL "Colon cancer history"
* #COLC "Colon cancer"
* #COM "Complex Regional Pain Syndrome"
* #CON "Constipation"
* #CONF "Confusion"
* #CONS "Constipation"
* #CONT "Contact Tracing"
* #COO "Cancer Of Oesophagoscopy"
* #COP "COPD"
* #COPD "COPD"
* #COT "Cancer Of Tonsils"
* #COU "Cough"
* #COUGH "Cough"
* #CP "Carpal Tunnel"
* #CPG "Cancer Of Parotid Gland"
* #CPL "Congenital pes planus, left foot"
* #CPN "Complication of Pregnancy NEC"
* #CPR "Cancer Prostate"
* #CPS "Cancer Paranasal Sinus"
* #CRA "Contracture, right ankle"
* #CRF "Contracture, right foot"
* #CRI "Chronic renal insufficiency"
* #CRK "Contracture, right knee"
* #CRM "CML, BCR/ABLPositive, not Achieve Remis"
* #CRO "Crohns"
* #CSA "Stress Anxiety"
* #CSG "Cancer Of Salivary Gland Or Duct"
* #CSL "Calcaneal spur, left foot"
* #CSR "Calcaneal spur, right foot"
* #CSUG "Cancer Of Submandibular Gland"
* #CT "Cubital Tunnel"
* #CT18 "Complete trisomy 18 Syndrome"
* #CT21 "Complete Trisomy 21 Syndrome"
* #CTD "Connective Tissue Disease"
* #CTN "Cancer therapies with nutrition risk"
* #CTO "Connective Tissue Disorder"
* #CTR "Change Of Trachae"
* #CTS "Carpal Tunnel Syndrome"
* #CU "Chronic uremia"
* #CURL "Calcified Ulcer"
* #CVC "Cancer Of Vocal Cords"
* #CX "Cervical Smear"
* #CYF "Cystic Fibrosis"
* #CYN "Cyst Neck"
* #CYS "Cyst"
* #CYSTFIB "Cystitis Fibrosis"
* #CYT "Cyst Throat"
* #D0101 "Behavioural Problems"
* #D0114 "Bladder Dysfunction"
* #D0115 "Blindness & Low Vision"
* #D0238 "Cataract Associated with Other Disorders"
* #D0239 "Cataract Secondary to Ocular Disorders"
* #D0325 "Corneal FB"
* #D0326 "Corneal Opacity & Other Disord of Cornea"
* #D0469 "Enuresis"
* #D0498 "Fasciitis"
* #D0499 "Feeding Difficulties & Mismanagement"
* #D0556 "Haematuria"
* #D0618 "Incontinence of Urine"
* #D062 "Inflammation of Eyelids"
* #D0694 "Mantoux Positive"
* #D0709 "Mixed Connective Tissue Disease"
* #D0795 "Obstructive Sleep Apnoea"
* #D1171 "Torsion of Testis"
* #D1178 "Training Re-Bladder Managements"
* #D1248 "Major Eye Trauma"
* #D509 "Iron deficiency anaemia, unspecified"
* #D630 "Anaemia in chronic diseases classified"
* #D649 "Anaemia, unspecified"
* #D696 "Thrombocytopenia, unspecified"
* #D700 "Agranulocytosis"
* #DAC "Dacryocystorhintostomy (Dcr)"
* #DASS "Dental assessment"
* #DBV "Deficiency-other specified B group vitam"
* #DC "Dupuytrens Contracture"
* #DCD "Developmental Coordination Disorder"
* #DCIS "DCIS breast"
* #DCP "Ductal Carcinoma Parotid"
* #DCS "Disorder of Cardiovascular System"
* #DCT "Disorder of Connective Tissue"
* #DDN "Dental Disorder NEC"
* #DDS "Disorder of Digestive System"
* #DEAP "Decrease of Appetite"
* #DECMOD "Decreased Mobility"
* #DED "Developmental Delay"
* #DEH "Dehydration"
* #DEL "Delirium"
* #DEM "Dementia"
* #DENA "Dental Assess"
* #DEP "Depression"
* #DEPO "Depo Provera"
* #DEQ "Dequervains"
* #DER "Dematitis"
* #DETE "Decayed Teeth"
* #DEV "Development Assess"
* #DFC "Diabetes Follow up from Community"
* #DFK "Disciform Keratitis"
* #DI1 "Diabetes T1DM"
* #DI2 "Diabetes T2DM"
* #DIA "Diabetes"
* #DIABU "Diabetic Ulcer"
* #DIAPHDIS "Diaphram Disorder"
* #DIB "Disorder of Back"
* #DIC "Dilated Cardiomyopthy"
* #DIG "Diabetes Gestational"
* #DIM "Dietary Management"
* #DIN "Diabetic Neuropathy"
* #DIP "Diplopia"
* #DIS "Dysphagia"
* #DISO "Disorientation"
* #DIV "Diverticulitis"
* #DLA "Dysplasia Nos"
* #DLF "Other acquired deformities of left foot"
* #DLM "Mass Lip"
* #DM1 "Type 1 Diabetes Mellitus"
* #DM2 "Type 2 Diabetes Mellitus"
* #DMS "Disorder of Muscular System"
* #DNS "Deviated Nasal Septum"
* #DO0 "Acute Inflammation of Orbit"
* #DO1 "Proptosis"
* #DO2 "Deform of Orbit Incl Craniofacial Disord"
* #DO3 "Other Disorders of the Orbit"
* #DOC "Drug or Chemical Induced"
* #DOE "Disorder of Eye"
* #DONOR "Donor Site"
* #DOS "Downs Syndrome"
* #DOT "Disorder of thyroid"
* #DOU "Disorder Of Uterus"
* #DP "Discharge Planning"
* #DRF "Deteriorating Renal Function"
* #DS "Downs Syndrome"
* #DT1 "Diabetes Type 1"
* #DT2 "Diabetes Type 2"
* #DTL "Oth acquired deformities of toes,left ft"
* #DTR "Other acquired deformities of toes,right"
* #DUC "Duke's C Colorectal Cancer"
* #DVT "Deep Vein Thrombosis"
* #DW "Difficulty in walking, NEC"
* #DWP "Diabetes with Nepropathy"
* #DYS "Dysphagia"
* #DYSA "Dysphagia"
* #DYSF "Dysfluency"
* #DYSO "Dysphonia"
* #DYSP "Dyspareunia"
* #DYSPNOEA "Dyspnoea"
* #DYSU "Dysuria"
* #E039 "Hypothyroidism, unspecified"
* #E059 "Thyrotoxicosis, unspecified"
* #E109 "Type 1 diabetes mellitus without complic"
* #E119 "Type 2 diabetes mellitus without complic"
* #E161 "Other hypoglycaemia"
* #E237 "Disorder of pituitary gland, unspecified"
* #E309 "Disorder of puberty, unspecified"
* #E669 "Obesity, unspecified"
* #E840 "Cystic fibrosis with pulmonary manifesta"
* #E849 "Cystic fibrosis, unspecified"
* #E878 "Other disorders of electrolyte and fluid"
* #EAD "Eating Disorder"
* #EAF "Effusion of ankle and foot"
* #EASS "ENT Assessment"
* #EBC "Ear Basal Cell Carcinoma"
* #EBCC "Ear Lesion Basal Cell Carcinoma"
* #EC "Endocervical Cancer"
* #ECC "ECC"
* #ECT "Ectropion"
* #ECZ "Eczema"
* #ED0 "Ptosis"
* #ED1 "Marcus Gunn"
* #ED2 "Haemangioma"
* #ED3 "Other Eyelid Disorders e.g. Cysts"
* #ED4 "Eyelid Synkinesis"
* #EEH "Erosion Ectropion Cervix"
* #EHY "Endometrial Hyplasia"
* #EIS "Endometriosis In Cutaneous Scar"
* #ELA "Effusion, left ankle"
* #ELB "Elbow Pain"
* #ELF "Effusion, left foot"
* #ELK "Effusion, left knee"
* #ELL "Spec enthesopathies left lwr limb exfoot"
* #ELSC "Ear Lesion Squamous Cell Carcinoma"
* #EM0 "Oculomotor Apraxia"
* #EM1 "Skew Deviation"
* #EM2 "DVD"
* #EM3 "Other Disorders of Eye Movement"
* #EM4 "Chronic Progr External Ophthalmoplegia"
* #EM5 "DHD"
* #ENA "Enteral Feeding - adult"
* #ENC "Encephalitis"
* #ENCAN "Endometrial Cancer"
* #ENCO "Encopresis"
* #END "Endocarditis"
* #ENDO "Endometriosis Unspecified"
* #ENL "Effusion of knee/lower leg"
* #ENP "Enteral Feeding - paediatric"
* #ENUR "Enuresis"
* #EOP "Endometriosis Of Pelvic"
* #EOU "Endometriosis Of Uterus"
* #EPBU "Epidermolysis Bullosa"
* #EPI "Epistaxes"
* #ERA "Effusion, right ankle"
* #ERD "Erectile Dysfunction"
* #ERF "Effusion, right foot"
* #ERK "Effusion, right knee"
* #ERL "Spec enthesopathies right lwr limb,excft"
* #ES0 "Constant esotropia"
* #ES1 "Infantile esotropia"
* #ES10 "Micro esotropia without identity"
* #ES11 "Micro esotropia with fully accom chara"
* #ES12 "Micro esotropia with Conv excess chara"
* #ES13 "Intermitt Esotropia-Divergence Weakness"
* #ES14 "Sudden Onset Esotropia"
* #ES15 "Esotropia Associated with High Myopia"
* #ES2 "Partially accommodative esotropia"
* #ES3 "Intermittent (conv. Excess) esotropia"
* #ES4 "Consecutive esotropia"
* #ES5 "Secondary esotropia"
* #ES6 "Other Esotropia"
* #ES7 "Intermittent (Fully accom) esotropia"
* #ES8 "Residual esotropia"
* #ES9 "Micro esotropia with identity"
* #ESC "Employment screening or clearance"
* #ESCC "Ear Squamous Cell Carcinoma"
* #EWING "Ewing Sarcoma"
* #EX0 "Constant Early Onset Exotropia"
* #EX1 "Intermittent exotropia"
* #EX10 "Constant Decompensated Exotropia"
* #EX2 "Consecutive exotropia"
* #EX3 "Secondary exotropia"
* #EX4 "Other Exotropia"
* #EX5 "Residual exotropia"
* #EX6 "Micro exotropia with identity"
* #EX7 "Micro exotropia without identity"
* #EX8 "intermittent Distance Exotropia"
* #EX9 "Intermittent Near Exotropia"
* #EXO "Exostosis"
* #EXT "Extractions"
* #EYAS "Eyes Assessment"
* #EYE "Eye Trauma"
* #EYE00 "Normal"
* #EYE01 "Cataract"
* #EYE02 "Alphakia & Other Lens"
* #EYE03 "Glaucoma"
* #EYE04 "Glaucoma Suspect"
* #EYE05 "Squint"
* #EYE06 "Amblyopia"
* #EYE07 "Refractive Error"
* #EYE08 "Blepharitis"
* #EYE09 "Dry Eye"
* #EYE10 "Lid Malposition"
* #EYE11 "Chalazion / Style"
* #EYE12 "Other Lid"
* #EYE13 "Keratitis"
* #EYE14 "Corneal Scar/Opacity/Oedema"
* #EYE15 "Corneal Degeneration/Dystrophy"
* #EYE16 "Keratoconus"
* #EYE17 "Pterygium"
* #EYE18 "Other Corneal"
* #EYE19 "Conjunctiva Disorders of"
* #EYE20 "Uvetis"
* #EYE21 "Hzo Herpes Zoster Ophthalmicus"
* #EYE23 "Lacrimal System Disorders of"
* #EYE24 "Orbit Disorders of"
* #EYE25 "Sclera & Episclera Disorders of"
* #EYE26 "Vitreous Disorders of"
* #EYE27 "Optic Nerve & Visual Pathways Disorde"
* #EYE28 "Iris & Ciliary Body Disorders of"
* #EYE29 "Chorioid Disorders of"
* #EYE30 "Diabetic Retinopathy"
* #EYE31 "Retinal Vascular Occlusion"
* #EYE32 "Armd Age Related Macular Degeneration"
* #EYE33 "Rd Defect Retinal Detachment Defect"
* #EYE34 "Other Retinal"
* #EYE35 "Penetrating Trauma"
* #EYE36 "Blunt Trauma"
* #EYE37 "Minor Trauma / Fb"
* #EYE38 "Other Injury"
* #EYE39 "Diabetic (Normal)"
* #EYE40 "Non Diabetic Retinopathy"
* #EYE99 "All Other"
* #F009 "Dementia in Alzheimer s disease, unspeci"
* #F030 "Unspecified dementia"
* #F201 "Schizophrenia Disorganised Type"
* #F419 "Anxiety disorder, unspecified"
* #F509 "Eating disorder, unspecified"
* #F840 "Childhood autism"
* #F900 "Disturbance of activity and attention"
* #FAI "Facial Injuries"
* #FAL "Fallopian"
* #FALLS "Falls"
* #FAP "Facial Pain"
* #FAS "Fetal Alcohol Syndrome"
* #FBE "Foreign Body Ear"
* #FBN "Foreign Body Nasal"
* #FCO "Follicular Cyst Of Ovary"
* #FCS "Family/Caregiver Concerns"
* #FCTD "FCT-Cancer"
* #FDC "Full Dental Clearance"
* #FEB "Febrile illness"
* #FELD "Frail Elderly"
* #FEP "Fibro Eopithelial Polyp"
* #FERT "Fertility"
* #FFB "Fractured Facial Bones"
* #FFL "Flat foot/pes planus (acquired),left foo"
* #FFR "Flat foot/pes planus (acquired),right fo"
* #FGR "Faulty Growth"
* #FGTW "Fungating Wound"
* #FI "Feeding Issues"
* #FIBR "Fibroadenoma"
* #FIE "Fillings & Extractions"
* #FIL "Fillings"
* #FIN "Female Infertility Nos"
* #FIS "Fissures"
* #FNS "Fractured Nose"
* #FORE "Foreskin Frenulum"
* #FORGNBDY "Foreign Body"
* #FRA "Fracture"
* #FRB "Fractured Facial Bones"
* #FRC "Fracture left Ankle"
* #FRJ "Fractured Jaw"
* #FRM "Fracture Mandibular"
* #FRX "Fragile X Syndrome"
* #FS "Frozen Shoulder"
* #FTT "Failure To Thrive"
* #FUNG "Fungal"
* #FUS "Fussy eating/Oral aversion"
* #FXJ "Fractured Jaw"
* #FXM "Fractured Mandibular"
* #FXZ "Fractured Zygomatic"
* #G200 "Parkinson Disease"
* #G350 "Multiple sclerosis"
* #G4090 "Epilepsy, unspecified, without mention"
* #G439 "Migraine, unspecified"
* #G458 "Other transient cerebral ischaemic"
* #G560 "Carpal tunnel syndrome"
* #G809 "Cerebral palsy, unspecified"
* #GAL "Gallstones"
* #GALL "Gallstones"
* #GALLP "Gallbladder polyp"
* #GAN "Ganglion"
* #GAR "Gouty Arthritis"
* #GARD "Gardasil Vaccination"
* #GAS "Gastrosch's"
* #GASCA "Gastric Cancer"
* #GASR "Gastritis"
* #GASS "Gynaecology assessment"
* #GAST "Gastroenteritis"
* #GBS "Guillion Barrie Syndrome"
* #GDD "Global Developmental delay"
* #GDDM "Gestational Diabetes"
* #GDS "Goldenhar Syndrome"
* #GEA "General Eye Assessment"
* #GED "Gestational Diabetes"
* #GEN "Gene Change"
* #GES "Genetic Syndrome"
* #GII "Gingivitis"
* #GIST "Gastrointestinal Stromal Tumour"
* #GLA "Glaucoma"
* #GLDR "Dry AMD"
* #GLGS "low risk glaucoma suspect"
* #GLHR "high risk glaucoma suspect"
* #GLI "Glioblastoma"
* #GLLR "Low risk Glaucoma"
* #GLNA "Non acute Glaucoma"
* #GLW "Wet AMD"
* #GMAST "Gynecomastia"
* #GMT "Goitre"
* #GOR "GORD"
* #GOU "Gout"
* #GOUT "Gout"
* #GPN "Gestational Proteniuria"
* #GRC "Growth Inside RT Cheek/Gum"
* #GSY "Genetic syndromes"
* #GT "Gouty Tophi"
* #GTT "Gestational Trophoblastic Tumour"
* #GU "Gastric Ulcer"
* #GUT "Gut disturbances"
* #H020 "Entropion and trichiasis of eyelid"
* #H021 "Ectropion of eyelid"
* #H029 "Disorder of eyelid, unspecified"
* #H269 "Cataract, unspecified"
* #H539 "Visual disturbance, unspecified"
* #H669 "Otitis media, unspecified"
* #H813 "Other peripheral vertigo"
* #H919 "Hearing loss, unspecified"
* #H931 "Tinnitus"
* #HAE "Haemorrhoids"
* #HAEM "Haemophilia"
* #HAEMC "Haemachromatosis"
* #HAEMOPTYS "Haemoptysis"
* #HAR "Hearing loss"
* #HAT "Haemarthrosis"
* #HATMA "Haematoma"
* #HBA "HBA1C > 100"
* #HCL "Hairy Cell Leukaemia"
* #HE0 "Esophoria Non Significant"
* #HE1 "Esophoria Significant"
* #HE2 "Exophoria Non Significant"
* #HE3 "Significant Exophoria"
* #HE6 "Pseudostrabismus"
* #HE7 "Orthophoria/ NAD"
* #HE8 "Other Heterophoria"
* #HE9 "Convergence Insufficiency"
* #HEA "Head Pain"
* #HEAM "Hemochromatosis"
* #HEARTFAIL "Heart Failure"
* #HED "Hearing Disorder"
* #HEF "Heart Failure"
* #HELP "Helplesssness"
* #HEM "Hemiplegia"
* #HEP "Hepatitis"
* #HEPB "Hepatitis B"
* #HEPC "Hepatitis C"
* #HER "Hernia"
* #HERB "Hernia Bilateral"
* #HERD "Hernia Diaphragmatic"
* #HERI "Hernia Inguinal"
* #HERL "Hernia Left"
* #HERPU "Hernia Protruding Umbilical"
* #HERR "Hernia Right"
* #HERV "Hernia Ventral"
* #HF "Heart Failure"
* #HGC "HGSIL, Cervix"
* #HGL "Hypoglycemia"
* #HIDS "Hidradenitis suppurativa"
* #HIN "Head Injury"
* #HIP "Hip Spica"
* #HIR "Hirschsprung Disease"
* #HIV "HIV/AIDS- Human immunodeficiency virus"
* #HNF "Hernia femoral"
* #HNH "Hernia hiatus"
* #HNI "Hernia incisional"
* #HNIG "Hernia inguinal"
* #HNU "Hernia umbilical"
* #HOD "Hormone Deficiency"
* #HON "HONK"
* #HP "Hearing Loss"
* #HPB "Hepatitis B"
* #HPOG "Hypoglycemia"
* #HPR "Hydronephrosis"
* #HPV "Human Papillomavirus"
* #HRL "Hallux rigidis, left foot"
* #HRP "Highlighted Result Risk Hpv-Dna Positive"
* #HRR "Hallux rigidis, right foot"
* #HRT "Heart Failure"
* #HSL "High Sugar Levels, T2DM"
* #HT "Hammer Toe"
* #HTL "Hammer toes (other), left foot"
* #HTR "Hammer toes (other), right foot"
* #HTS "Hepatosplenomegaly"
* #HUD "Huntington's Disease"
* #HUN "Huntingtons Disease"
* #HVL "Hallux valgus, Bunion left foot (acqurd)"
* #HVR "Hallux valgus, Bunion right foot (acqrd)"
* #HWJ "Hepatomegaly with jaundice"
* #HWJA "Hepatomegaly without jaundice"
* #HYCAL "Hypercalcaemia"
* #HYD "Hydronephrosis"
* #HYE "Hyperemesis"
* #HYP "HypoGlycaemia"
* #HYPE "Hyperglycemia"
* #HYPOXEMIA "Hypoxemia"
* #HYPT "Hyperparathyroidism"
* #HYT "Hyperthyroidism"
* #HZ "Herpes Zoster"
* #I100 "Essential (primary) hypertension"
* #I139 "Hypertensive heart and kidney disease, u"
* #I209 "Angina pectoris, unspecified"
* #I489 "Atrial fibrillation and atrial flutter,"
* #I500 "Congestive heart failure"
* #I640 "Stroke, not specified as haemorrhage or"
* #I868 "Varicose veins of other specified sites"
* #IAR "Inflammatory Arthropathy"
* #IBB "Infammatory Bowel disease"
* #IBD "Inflammatory Bowel Disease"
* #IBE "Incomplete Bladder Emptying"
* #IBS "Irritable Bowel Syndrobe"
* #ICD "Irritant Contact dermatitis"
* #ICH "Interstitial Cystitis With Haematuria"
* #ICWH "Interstitial Cystitis Without Haematuria"
* #IDEF "Immunoglobulin Deficiency"
* #IDM "Type 1"
* #IF "Incontinence Functional"
* #IFD "Intellectual Functioning Disability"
* #Ile "Ileitis"
* #IM "Impacted Wisdom Tooth"
* #IMM "Immobility"
* #IMP "Impertigo"
* #IMT "Impacted Wisdom Teeth"
* #INA "Inflammatory Arthritis"
* #INAP "Increase of Appetite"
* #INB "Inborn Errors of Metabolism"
* #INC "Incontinence"
* #IND "Intellectual Disability"
* #INF "Infection"
* #INJ "Head Injury"
* #INTLUNGDS "Interstitial Lung Disorder"
* #IO "Incontinence Overflow"
* #IOB "Injury of Back"
* #IOT "Infection Of Trachae"
* #IRA "Infections resistant to Antibiotics"
* #IRR "Irritable Bowel Syndrome"
* #IS "Incontinence Stress"
* #ISB "Increasing Sob"
* #ISC "Ischaemic Cardiomyopathy"
* #ISHC "Ischemic Heart Disease"
* #IT "Intraorbital Tumour"
* #ITO "Infertility-Tubal Origin"
* #ITR "Incontinence Transient"
* #IU "Incontinence Urinary"
* #IUCD "Iucd Removal"
* #IUO "Infertility-Uterine Origin"
* #IVA "IV ABS in Home"
* #IWT "Impacted Wisdom Tooth"
* #J029 "Acute pharyngitis, unspecified"
* #J050 "Acute obstructive laryngitis [croup]"
* #J339 "Nasal polyp, unspecified"
* #J350 "Chronic tonsillitis"
* #J370 "Chronic laryngitis"
* #J400 "Bronchitis, not specified as acute or ch"
* #J449 "Chronic obstructive pulmonary disease, u"
* #J459 "Asthma, unspecified"
* #J470 "Bronchiectasis"
* #JADE "Jade Removal"
* #JAF "Joint derangement, ankle/foot"
* #JAU "Jaundice"
* #JAW "Jaw Pain"
* #JBP "Back Pain"
* #JCA "Juvenile Chronic Arthiritis"
* #JOP "Joint Pain"
* #JP "Joint Pain"
* #K029 "Dental caries, unspecified"
* #K200 "Oesophagitis"
* #K219 "Gastro-oesophageal reflux disease withou"
* #K257 "Gastric ulcer, chronic without haemorrha"
* #K269 "Duodenal ulcer, unspecified as acute or"
* #K469 "Unspecified abdominal hernia without obs"
* #K500 "Crohn s disease of small intestine"
* #K519 "Ulcerative colitis, unspecified"
* #K566 "Other and unspecified intestinal obstruc"
* #K5790 "Diverticulosis of intestine, part unspec"
* #K580 "Irritable bowel syndrome with diarrhoea"
* #K589 "Irritable bowel syndrome without diarrho"
* #K590 "Constipation"
* #K621 "Rectal polyp"
* #K628 "Other specified diseases of anus and rec"
* #K649 "Haemorrhoids, unspecified"
* #K739 "Chronic hepatitis, unspecified"
* #K768 "Other specified diseases of liver"
* #K769 "Liver disease, unspecified"
* #K819 "Cholecystitis, unspecified"
* #K859 "Acute pancreatitis, unspecified"
* #K861 "Other chronic pancreatitis"
* #K900 "Coeliac disease"
* #K929 "Disease of digestive system, unspecified"
* #KDF "Renal Failure"
* #KID "Kidney Disease"
* #KLS "Klinefelters Syndrome"
* #KUD "Kufs Disease"
* #L050 "Pilonidal cyst with abscess"
* #L059 "Pilonidal cyst without abscess"
* #L309 "Dermatitis, unspecified"
* #L820 "Seborrhoeic keratosis"
* #LA0 "Cataract"
* #LA1 "Dislocated Lens"
* #LA2 "Other Lens Anomalies"
* #LA3 "Congenital Cataract"
* #LAB "Labyrinthitis"
* #LABY "Labyrinths"
* #LAD "Lada"
* #LAP "Lower Abdo Pain"
* #LAR "Laryngectomy"
* #LARYNGDIS "Laryngeal Disorder"
* #LAT "Lactose intolerance"
* #LCA "Lip Cancer"
* #LCAN "Lung Cancer"
* #LCTN "Laceration"
* #LDC "Lower Dental Clearance"
* #LE "Lupus ervthematosus"
* #LEG "Leg Pain"
* #LEL "Leaky Leg"
* #LES "Lesion/Cyst/Lump"
* #LEU "Leukoplakia"
* #LFM "Large Fetus Malporportion"
* #LGC "LGSIL, Cervix"
* #LHO "LHO appreciation"
* #LICAN "Liver Cancer"
* #LIL "Low Iron Levels"
* #LIP "Lichen Plantus"
* #LIPO "Lipoma"
* #LIS "Lichen sclerosus"
* #LISC "Linear Scleroderma"
* #LIT "Lip Tie"
* #LIV "Liver disease"
* #LLB "Leaky Leg Bilateral"
* #LLG "Large Lymph Glands"
* #LLL "Lesion of plantar nerve, left lwr limb"
* #LMS "Liver Metastatic"
* #LNEUT "Low Neutrophils"
* #LP "Lichen Planus"
* #LPP "Lymphadenopathy"
* #LPR "Lesion of plantar nerve,right lower limb"
* #LQT "Long QT Syndrome"
* #LS0 "Epiphora"
* #LS1 "Dry Eye"
* #LS2 "Other Lacrimal Disorders"
* #LSC "Larynx Squamous Cell Carcinoma"
* #LSCC "Lip Squamous Cell Carcinoma"
* #LSCL "Lichen Sclerosus"
* #LSH "Shin Wound"
* #LT "Lip Tie"
* #LUMP "Lump"
* #LUN "Lung Infection"
* #LUP "Lupus"
* #LYM "Lymphoma"
* #LYMP "Lymphoma"
* #LYMPA "Lymphorrhea"
* #LYMPD "Lymphoedema"
* #M1099 "Gout, unspecified, site unspecified"
* #M1389 "Other specified arthritis,site unspecifi"
* #M201 "Hallux valgus (acquired)"
* #M229 "Disorder of patella, unspecified"
* #M2454 "Contracture of joint, hand"
* #M2559 "Pain in a joint, site unspecified"
* #M653 "Trigger Finger"
* #M80700 "SQUAMOUS CELL CARCINOMA, NOT OTHERWISE S"
* #M80900 "BASAL CELL CARCINOMA, NOT OTHERWISE SPEC"
* #M8190 "Unspecified osteoporosis, multiple sites"
* #M8429 "Delayed union of fracture, site unspecif"
* #M97320 "MULTIPLE MYELOMA"
* #M98000 "LEUKAEMIA, NOT OTHERWISE SPECIFIED"
* #M99610 "PRIMARY MYELOFIBROSIS"
* #MA0 "Browns"
* #MA1 "Duanes"
* #MA10 "Sagging Eye Syndrome"
* #MA2 "Trauma/MechLimit DuctOfEyeMuscl IncBO#"
* #MA3 "Strabismus due to Adhesions e.g. post-op"
* #MA4 "Ocular Myasthenia Gravis"
* #MA5 "Other Limitations-MultipleSclerosis etc"
* #MA6 "A/V Patterns"
* #MA7 "Inferior Oblique Overaction"
* #MA8 "Thyroid Eye Disease"
* #MA9 "Ocular lgG4 Disease"
* #MAL "Malignancy"
* #MALN "Malnutrition"
* #MALP "Malpresentation"
* #MAR "Marfin Syndrome"
* #MAS "Mastoidectomy"
* #MASD "Moisture Associated Skin Damage"
* #MAVUL "Mixed Arterial/Venous Ulcer"
* #MAX "Maxillary Sinus"
* #MC "Multiple Complications (Specify)"
* #MCER "Mucosal Cleft Extending Rectal Wall"
* #MCL "Mantle Cell Lymphoma"
* #MCP "Monoplegic Cerebral Palsy"
* #MD "Meningococcal Disease"
* #MDK "Multicystic Dysplastic Kidney"
* #MDN "Menopausal Disorder Nos"
* #MDS "Myelodysplastic Syndrome"
* #ME "Measles"
* #MED "Multiple Episodes Of Dizziness"
* #MEE "Middle Ear Effusions"
* #MEI "Middle ear infections / discharge"
* #MEL "Melanoma"
* #MELM "Melanoma metastatic"
* #MELSIT "Melanoma in-situ"
* #MEML "Memory Loss"
* #MEN "Meniere's Disease"
* #MER "Merkle Cell"
* #MES "Mesothelioma"
* #MET "Metastasic"
* #MF "Mickey Feeding"
* #MGC "Mixed Germ Cell"
* #MIC "Micronutrient deficiency"
* #MIG "Migraines"
* #MINO "Minor Surgical Follow Up"
* #MJP "Muscle And Joint Pains"
* #MLCY "Malignancy"
* #MLF "Metatarsalgia, left foot"
* #MM "Multiple Myeloma"
* #MMMN "Morton's metatarsalgia/Morton's neur"
* #MMU "Medial Malleolus Ulcer"
* #MND "Motor Neuron Disease"
* #MNL "Malignant Neoplasm Of Left Ovary"
* #MNR "Malignant Neoplasm Of Right Ovary"
* #MODY "Maturity Onset of the Young"
* #MON "Monoarthritis"
* #MOU "Malposition Of Uterus"
* #MRCA "MRSA Carrier"
* #MRF "Metatarsalgia, right foot"
* #MRSA "MRSA Conditions"
* #MS "Multiple Sclerosis"
* #MSC "Multiple Sclerosis"
* #MSCC "Mouth Squamous Cell Carcinoma"
* #MSY "Menopausal Syndrome"
* #MU "Mumps"
* #MUC "Muscloskeletal Conditions"
* #MUD "Multiple Disability"
* #MULS "Multiple Sclerosis"
* #MULT "Multiparity"
* #MUS "Multiple Sclerosis"
* #MW "Muscle weakness (generalized)"
* #MYG "Myringotomy - Grommets"
* #MYI "Myocardial Infarction"
* #MYO "Myocarditis"
* #N133 "Other and unspecified hydronephrosis"
* #N189 "Chronic kidney disease, unspecified"
* #N190 "Unspecified kidney failure"
* #N200 "Calculus of kidney"
* #N201 "Calculus of ureter"
* #N230 "Unspecified renal colic"
* #N309 "Cystitis, unspecified"
* #N390 "Urinary tract infection, site not specif"
* #N433 "Hydrocele, unspecified"
* #N459 "Orchitis, epididymitis and epididymo-orc"
* #N470 "Redundant prepuce, phimosis and paraphim"
* #N630 "Unspecified lump in breast"
* #N739 "Female pelvic inflammatory disease, unsp"
* #N759 "Disease of Bartholin s gland, unspecifie"
* #N768 "Other specified inflammation of vagina"
* #N809 "Endometriosis, unspecified"
* #N819 "Female genital prolapse, unspecified"
* #N849 "Polyp of female genital tract, unspecifi"
* #N879 "Dysplasia of cervix uteri, unspecified"
* #N939 "Abnormal uterine and vaginal bleeding,"
* #N959 "Menopausal and perimenopausal disorder,"
* #NAC "Nasopharyngeal Carinoma"
* #NAMD "n AMD"
* #NAO "Nasal Obstruction"
* #NAP "Nasal Polypectomy"
* #NAS "Nasopharyngeal"
* #NBCC "Nasal Basal Cell Carcinoma"
* #NC "Neurological Complication (specify)"
* #NDM "Type 2"
* #NEB "Neurogenic Bladder"
* #NEO "Newborn Hearing Screening"
* #NEP "Nephrotic Syndrome"
* #NER "Neurofribromatosis"
* #NERV "Nerve Pain"
* #NET "Necrotic Tongue"
* #NEU "Neuroblasts"
* #NEUDT "Neuro-endocrine tumour"
* #NEUT "Neuro-endocrine Tumour"
* #NGON "Neisseria Gonorrhoea"
* #NHL "Non Hodgkins Lymphoma"
* #NI "No Impairment"
* #NID "Non Imflammatory Disorder"
* #NLBC "Nasal Lesion Basal Cell Carcinoma"
* #NPL "Neoplasms"
* #NPP "NeuropathIc Pain"
* #NPR "Normal Pregnancy"
* #NS "Nephrotic syndrome"
* #NSC "Nasal Squamous Cell Carcinoma"
* #NSCC "Nasal Lesion Squamous Cell Carcinoma"
* #NSD "No Specific Diagnosis"
* #NSTEMI "NSTEMI"
* #NSWT "Night Sweats"
* #NUT "Nutritional Disorder"
* #NVC "Nodule On Vocal Cord"
* #NY0 "Manifest nystagmus"
* #NY1 "Latent nystagmus"
* #NY2 "Manifest latent nystagmus"
* #NY3 "Congenital nystagmus"
* #NY4 "See-saw nystagmus"
* #NY5 "Rotary nystagmus"
* #NY6 "Nystagmus with albinism"
* #NY7 "Other Nystagmus"
* #NY8 "Voluntary Nystagmus"
* #NYG "Nystagmus"
* #O099 "Unspecified duration of pregnancy"
* #O159 "Eclampsia, unspecified as to time period"
* #O160 "Unspecified maternal hypertension"
* #O218 "Other vomiting complicating pregnancy"
* #O321 "Maternal care for breech presentation"
* #O419 "Disorder of amniotic fluid and membranes"
* #O440 "Placenta praevia specified as without ha"
* #O469 "Antepartum haemorrhage, unspecified"
* #OASS "Orthopaedic assessment"
* #OBE "Obesity"
* #OC "Ophthalmic Complication"
* #OCA "Other Cancers"
* #OCAN "Ovarian Cancer"
* #OCL "Oral Cavity Lesion"
* #OCN "Other Specified Noninflammatory"
* #ODM "Other Specific Diabetes Mellitus"
* #ODN "Opthlamic Disorder NEC"
* #ODS "Other Disorder of the Skin"
* #OECA "Oesophageal cancer"
* #OES "Oesophageal"
* #OESA "Oesophageal achalasis"
* #OESO "Oesophagitis"
* #OEST "Oesophageal stenosis"
* #OHS "Occular Hypertension Spikes"
* #OM "Obesity Morbid"
* #OME "Otitis Media Effusion"
* #OMET "Otitis Media Effusion,Flat Tympanograms"
* #ON0 "Optic Atrophy"
* #ON1 "Optic Nerve Hypoplasia"
* #ON2 "Coloboma"
* #ON3 "Papillodema"
* #ON4 "Optic Neuritis"
* #ON5 "Other Optic Nerve Anomalies"
* #ONC "Oncology"
* #ONH "Optic Nerve Hypoplasia"
* #OO "Other Obesity"
* #OOC "Other Ovarian Cysts"
* #ORAL "Oral Mucosa Lesion"
* #ORCH "Orchidopexy"
* #OS "Oesophageal Stricture"
* #OSA "Osa (Oversized Adenoids)"
* #OSD "Obstructive Sleep Disorder"
* #OSN "Other Specified Noninflammatory"
* #OSP "Osteoporosis"
* #OST "Osteomyelitis"
* #OTH "Other"
* #OTHRESP "Other Respiratory"
* #OTO "Otosclerosis"
* #OTP "Opthlamic Puritis"
* #OVA "Ovarian"
* #OW "Overweight"
* #P0730 "Extremely low birth weight 750 - 999g"
* #P700 "Syndrome of infant of mother with gestat"
* #PA "Abdominal Pain"
* #PA0 "Adie"
* #PA1 "Afferent Defect"
* #PA2 "Aniridia"
* #PA3 "Anisocoria"
* #PA4 "Argyll Robertson"
* #PA5 "Coloboma"
* #PA6 "Horners"
* #PA7 "Other Pupils Defects"
* #PAHL "Partial Hearing Loss"
* #PAINCHEST "Pain Chest"
* #PAL "Palliative Care"
* #PAN "Pancreatic"
* #PANCA "Pancreatic cancer"
* #PANCY "Pancytopaenia"
* #PANI "Pancreatic Insufficiency"
* #PAP "Pelvic And Perineal Pain"
* #PAR "Paraplegia"
* #PARK "Parkinsons Disease"
* #PAS "Pre-Auricular Sinus"
* #PAST "Pre Auricular Sinus Tract Abscess"
* #PBA "Pump, Diabetes advice"
* #PBC "Pinna Basal Cell Carcinoma"
* #PBE "Occular Pain NEC"
* #PBEH01 "ADHD / ODD"
* #PBEH99 "Behaviour - Other"
* #PBF "Premature Baby Follow up"
* #PBH "Hand Pain"
* #PBK "Knee Pain"
* #PBL "Postmenopausal Bleeding"
* #PBM "Plasmacytoma Bilat Maxillary Sinus"
* #PC "PCOS"
* #PCAN "Prostrate Cancer"
* #PCAR01 "Aortic Stenosis"
* #PCAR02 "ASD"
* #PCAR03 "AV Canal / AVSD"
* #PCAR04 "Murmur"
* #PCAR05 "Paroxysmal SVT / Arrhythmias"
* #PCAR06 "Pulmonary Hypertension"
* #PCAR07 "Pulmonary Stenosis"
* #PCAR08 "Rheumatic Fever / Valve Replacement"
* #PCAR09 "Tetralogy of Fallot"
* #PCAR10 "TGA"
* #PCAR11 "VSD"
* #PCAR12 "Coarctation Aorta"
* #PCAR99 "Other - Cardiac"
* #PCD "Poorly Controlled Diabetes"
* #PCS "Previous Caesarean Section"
* #PCYST "Pancreatic Pseudocyst"
* #PD "Dont Use - Parkinson's Disease"
* #PDEV01 "Autism / Aspergers"
* #PDEV02 "Chromosome - Other"
* #PDEV03 "Developmental Delay"
* #PDEV04 "Down Syndrome"
* #PDEV05 "Dymorphic Syndrome"
* #PDEV06 "Learning Disorder"
* #PDEV08 "Speech/Language Delay"
* #PDEV09 "Multiple Major Handicap"
* #PDEV99 "Other - Developmental"
* #PECAN "Peritoneal Cancer"
* #PED "Pancreatic Exocrine Disease"
* #PEE "Perforated Eardrum"
* #PEL "Pelvicalyceal Dilation"
* #PEN "Pending Surgery"
* #PEND01 "Adrenal - Other"
* #PEND02 "Congenital Adrenal Hyperplasia"
* #PEND03 "Diabetes"
* #PEND04 "Hypopituitarism / GH Deficiency"
* #PEND05 "Hypothyroidism"
* #PEND06 "Puberty - Early / Delayed"
* #PEND07 "Short Stature (Non GH)"
* #PEND08 "Turner Syndrome"
* #PEND99 "Other - Endocrine"
* #PENI "Penile Hypospadias"
* #PER "Pertussis"
* #PERIA "Perianal Abscess"
* #PERIN "Perineal Groove"
* #PERS "Personality Disorder"
* #PEY "Peyronies"
* #PF "Peg Feeding"
* #PFF "Plantar fascial fibromatosis"
* #PFG "Poor Fetal Growth"
* #PFH "Polyps Family History"
* #PFIS "Perianal Fistula"
* #PGM "Pterygium"
* #PGO "Parotid Gland Obstruction"
* #PGUT01 "Congenital Gut Anomalies"
* #PGUT02 "Constipation / Encopresis"
* #PGUT03 "GE Reflux / Oesophagitis"
* #PGUT04 "Liver Disease"
* #PGUT05 "Malabsorption"
* #PGUT06 "Recurrent Abdominal Pain"
* #PGUT07 "Inflammatory Bowel Disease"
* #PGUT99 "Other - Gut / Liver"
* #PH "Polyps History"
* #PHA "Pharyngitis"
* #PHAE01 "Anaemia"
* #PHAE02 "Haemaphilia / Bleeding Disorders"
* #PHAE03 "ITP"
* #PHAE04 "Other Haematology"
* #PHAE05 "Leukaemia"
* #PHAE06 "Brain Tumours"
* #PHAE99 "Other - Oncology"
* #PHAN "Phantom Pain"
* #PHD "Physical Disabillity"
* #PHI "Phimosis"
* #PHL "Permanent Hearing Loss"
* #PHLE "Phlebotomy"
* #PIDTI "Suspected Deep Tissue Injury"
* #PIL "Pinna Lesion - Wolfe Graft"
* #PIN "Parasitic Infection"
* #PINY "Pancreatic insufficiency"
* #PLEURLDIS "Pleural Disorder"
* #PLM "Plasmacytoma Left Maxillary Sinus"
* #PLN "Pain in left knee"
* #PLOC01 "Arthritis /Arthralgia - Other"
* #PLOC02 "JCA / JIA"
* #PLOC03 "Muscular Dystrophy / Myopathy"
* #PLOC04 "SLE"
* #PLOC05 "Spina Bifida"
* #PLOC06 "Spinal - Other"
* #PLOC99 "Other - Locomotion / Rheumatology"
* #PLP "Prolonged Pregnancy"
* #PLPR "Placenta Previa"
* #PLU "Ulcer Posterior Leg"
* #PLYM "Primary Lymphoedema"
* #PMA "Pain Lwr Rt Mandibular Area"
* #PMEN "Premature Menopause"
* #PMIS01 "Allergies / Food Intolerance"
* #PMIS02 "Chronic / Post Viral Fatigue"
* #PMIS03 "Failure to Thrive"
* #PMIS04 "Feeding Difficulties"
* #PMIS05 "Immune Defect / Recurrent Infections"
* #PMIS06 "Non Accidental Injury / Child Abuse"
* #PMIS07 "Obesity / Weight Gain"
* #PMIS08 "Irritable Infant/Feeding Difficulties"
* #PMIS09 "NAI/Abuse"
* #PMIS99 "Other"
* #PMN "Perimenopausal Menorrhagia"
* #PN "Neck Pain"
* #PNC "Pancreatitis"
* #PNE "Pneumonia"
* #PNEU01 "Cerebral Palsy / Hypertonia"
* #PNEU02 "Epilepsy"
* #PNEU03 "Eyes / Squint / Blind"
* #PNEU04 "Febrile Convulsions"
* #PNEU05 "Headaches / Migraine"
* #PNEU06 "Hydrocephalus / PVL / Cysts etc"
* #PNEU07 "Hypotonia / Clumsy / Dyspraxia"
* #PNEU08 "Meningitis Followup"
* #PNEU09 "Microcephaly"
* #PNEU10 "Shull Shape / Plagio / Brachycephaly"
* #PNEU11 "Tics / Tourettes"
* #PNEU12 "Head Injury"
* #PNEU99 "Other Neurological"
* #PNEUMONIA "Pneumonia"
* #PNEUMTHRX "Pneumothorax"
* #PNNF01 "Prematurity"
* #PNNF99 "Other Neonatal follow-up"
* #PO "Pulmonary Oedema"
* #POH "Portal Hytension"
* #POL "Polytrichia"
* #POLY "Polycythemia Vera"
* #POM "Polymyalgia"
* #POOR "Poor Dentition"
* #POPP "Progesterone Only Pill"
* #POPW "Open Wound"
* #POS "Poor Spirometry"
* #POST "Postherpetic Neuralgia"
* #POV "Polyp Of Vulva"
* #PPCYST "Pancreatic Pseudocyst"
* #PRC "Prostate Cancer"
* #PRD "Post Retinal Detachment"
* #PRE "Prematurity"
* #PREE "Preeclampsia"
* #PREG "Pregnancy Counselling"
* #PREN01 "Enuresis"
* #PREN02 "Hydronephrosis / Congenital Anomalies"
* #PREN03 "Nephrotic Syndrome / Glomerulonephritis"
* #PREN04 "UTI"
* #PREN05 "Vesicoureteric Reflux"
* #PREN99 "Other - Renal"
* #PREPOSTCI "Pre/Post Cardiac Intervention"
* #PRES01 "AlTE/Apnoea"
* #PRES02 "Asthma"
* #PRES03 "BPD/CLD"
* #PRES04 "Cystic Fibrosis"
* #PRES05 "Strider / Laryngo / Tracheomalacia"
* #PRES06 "Lower Respiratory Infection"
* #PRES07 "Otitis Media / URTI"
* #PRES08 "OSA / Sleep Disordered Breathing"
* #PRES09 "Rhinitis - Allergic"
* #PRES10 "TB / TB Contact"
* #PRES11 "Bronchiectasis"
* #PRES99 "Other Respiratory"
* #PRF "Pain in right ankle & joints right foot"
* #PRK "Pain in right knee"
* #PRM "Plasmacytoma Right Maxillary Sinus"
* #PRO "Prostate"
* #PROC "Proctitis"
* #PRS "Pressure Sores"
* #PRS1 "Pressure Injury - Stage 1"
* #PRS2 "Pressure Injury - Stage 2"
* #PRS3 "Pressure Injury - Stage 3"
* #PRS4 "Pressure Injury - Stage 4"
* #PRSUS "Pressure Injury  Unstageable"
* #PRU "Pruritis"
* #PS0 "Acquired III Nerve Palsy - Complete"
* #PS00 "Acquired Bilateral CN III"
* #PS1 "Acquired III Nerve Palsy - Superior Div"
* #PS10 "Total External Ophthalmoplegia"
* #PS11 "Internuclear Ophthalmoplegia"
* #PS12 "Supra Nuclear Palsy"
* #PS13 "Other Paralytic Strabismus"
* #PS14 "Acq III Nerve Palsy - with Pupil Sparing"
* #PS15 "Acq III Nerve Palsy with Aberrant Regene"
* #PS16 "Congenital VI"
* #PS17 "Double Elevator Palsy"
* #PS18 "Cyclic Oculomotor Palsy"
* #PS19 "Mobius Syndrome"
* #PS2 "Acquired III Nerve Palsy - Inferior Div"
* #PS20 "Congenital III"
* #PS21 "Congenital IV"
* #PS3 "Acquired IV Nerve Palsy"
* #PS4 "Acquired VI Nerve Palsy"
* #PS5 "Acquired Mixed nerve palsies"
* #PS6 "Acquired Medial Rectus Palsy"
* #PS7 "Acquired Superior Rectus Palsy"
* #PS8 "Acquired Inferior Rectus Palsy"
* #PS9 "Acquired Inferior Oblique Palsy"
* #PSC "Pinna Squamous Cell Carcinoma"
* #PSI "Pilonidal Sinus"
* #PSKI01 "Boils / Impetigo / Infections"
* #PSKI02 "Eczema"
* #PSKI03 "Naevi / Haemangioma / Vascular Malformat"
* #PSKI99 "Other - Skin"
* #PSO "Psorisis"
* #PST "Preauricular Skin Tag"
* #PSUR01 "Paediatric Surgery"
* #PSY "Psychogenic Pain"
* #PSYD "Psychotic Disorder"
* #PT "Toe Pain"
* #PTIS "Pancreatitis"
* #PTL "Posterior tibial tendinitis, left leg"
* #PTM "Prostate Metstatic"
* #PTR "Posterior tibial tendinitis, right leg"
* #PUJ "Puj Obstruction"
* #PUL "Pressure Ulcer"
* #PULMONVAS "Pulmonary Vascular Disorder"
* #PULRHB "Pulmonary Rehab"
* #PUO "Pyrexia"
* #PUT "Pump Therapy"
* #PVD "Peripheral Vascular Disease"
* #PYE "Pyelonephritis"
* #PYG "Pyoderma Gangrenosum"
* #Q5310 "Undescended testicle, unilateral, unspec"
* #Q549 "Hypospadias, unspecified"
* #QCP "Quadriplegic Cerebral Palsy"
* #QUA "Quadriplegia"
* #R002 "Palpitations"
* #R068 "Other and unspecified abnormalities of b"
* #R074 "Chest pain, unspecified"
* #R104 "Other and unspecified abdominal pain"
* #R180 "Ascites"
* #R194 "Change in bowel habit"
* #R310 "Unspecified haematuria"
* #R330 "Retention of urine"
* #R418 "Other and unspecified symptoms and signs"
* #R420 "Dizziness and giddiness"
* #R529 "Pain, unspecified"
* #R530 "Malaise and fatigue"
* #R540 "Senility"
* #R550 "Syncope and collapse"
* #R568 "Other and unspecified convulsions"
* #R609 "Oedema, unspecified"
* #R634 "Abnormal weight loss"
* #R635 "Abnormal weight gain"
* #R730 "Elevated blood glucose level"
* #RA0 "Refractive Error"
* #RA01 "Hypermetropia"
* #RA02 "Myopia"
* #RA03 "Hypermetropic Astigmatism"
* #RA04 "Myopic Astigmatism"
* #RA05 "Mixed Astigmatism"
* #RA06 "Hypermetropic Anisometropia"
* #RA07 "Myopic Anisometropia"
* #RA08 "Astigmatic Anisometropia"
* #RA09 "Presbyopia"
* #RA10 "Accommodative Spasm"
* #RAD "Raynaud's Disease"
* #RAF "Rheumatoid arthritis, ankle/foot"
* #RAP "Raynauds Phenomenon"
* #RAS "Renal Artery Stenosis"
* #RC "Rectal prolapse"
* #RCAN "Rectal Cancer"
* #RCC "Renal Cell Cancer"
* #RCCAN "Renal Cell Cancer"
* #RE3 "Other Retinal Disorders"
* #RE4 "Diabetic Retinopathy"
* #REC "Renal Complications"
* #REF "Reflux"
* #REN "Renal stones"
* #RES "Restorations"
* #RESPFAIL "Respiratory Failure"
* #RESU "Results"
* #RET "Retinopathy Screening"
* #RETC "Rectal Carcinoma"
* #RFI "Renal failure or impairment"
* #RGO "Reflux Gastro-oesophageal"
* #RH "Rheumatic Fever"
* #RHA "Rheumatoid Arthritis"
* #RHC "Referred to other HCP"
* #RHE "Rhematoid Arthritis"
* #RHF "Rheumatic Fever"
* #RHI "Rhinitis"
* #RI "Renal Issues"
* #RIL "Raised Iron Levels"
* #RIN "Ringworm"
* #RIUD "Retained IUCD in Pregnancy"
* #ROC "Root Canal"
* #RR "Retained Root"
* #RRE "Recurring Red Eye"
* #RRF "Rising Renal Function"
* #RUB "Rubella"
* #RUP "Rupture"
* #RUTI "Recurrent Uti"
* #RVU "Recurrence Venous Ulcers"
* #SA "Staphylococcal aureus"
* #SAL "Stiffness of ankle left"
* #SAR "Sarcoidosis"
* #SARC "Sarcoma"
* #SARCOIDOS "Sarcoidosis"
* #SASS "Surgical Assessment"
* #SB "Spina Bifida"
* #SBW "Small Bladder Volume"
* #SC "Social Circumstances"
* #SCA "Scale"
* #SCAB "Scabies"
* #SCAN "Stomach Cancer"
* #SCC "Scale & Clean"
* #SCCSIT "Squamous cell ca in-situ"
* #SCG "Squamous Cell Cancer Gum"
* #SCH "Schizophrenia"
* #SCI "Severe Combined Immunodeficiency"
* #SCK "Sickle Cell Disease"
* #SCL "Scleroderma"
* #SCM "Squamous Cell Cancer Mouth"
* #SCROM "Scrotal Mass"
* #SCROS "Scrotum Swelling"
* #SD "Seborrheic dermatitis"
* #SDC "Severe Carries"
* #SDI "Segmental&somatic dysfn of ilium/sacroi"
* #SDL "Segmental & somatic dysfunction lumbar"
* #SDR "Scar Revision"
* #SDT "Segmental & somatic dysfunction thoracic"
* #SECYST "Sebaceous cyst"
* #SED "Sensory Disabillity"
* #SEMI "Seminoma"
* #SEP "Septoplasty"
* #SEPT "Septorhinoplasty"
* #SFD "Suspected Fetal Demise"
* #SHA "Self Harming"
* #SHIN "Shingles"
* #SHL "Sensorineural hearing loss"
* #SHO "Shoulder Pain"
* #SHRK "Shrunken Kidney"
* #SI "Stress Incontinence"
* #SIN "Sinusitis"
* #SJS "Sjogrens Syndrome"
* #SKGR "Skin Graft"
* #SKI "Skin Cancer"
* #SKM "Skin Metastatic"
* #SL "Skin Lesion"
* #SLA "Sprain - unspecified ligament left ankle"
* #SLF "Stiffness of left foot, NEC"
* #SLR "Sprain - unspec ligament of right ankle"
* #SM "Sarcoma Metastatic"
* #SMA "Spinal Muscle Atrophy"
* #SML "Strain-unspec muscles&tendons lwr L leg"
* #SMR "Strain-unspec muscles&tendons lwr R leg"
* #SMT "Submerged tooth"
* #SN "Snoring"
* #SO "Sepsis Other"
* #SOB "SOB"
* #SOC "Stricture/Stenosis Of Cervix"
* #SOU "Straining On Urination"
* #SPB "Spina Bifida"
* #SPD "Spastic Diplegia"
* #SPI "Spinal Injury"
* #SPL "Soft Palate Lesion"
* #SPR "Sprain"
* #SPRA "Sero-Positive Rheumatoid Arthritis"
* #SQU "Squint"
* #SRF "Stiffness of right foot, NEC"
* #SSC "Supraglottis Sqaumous Cell Carcinoma"
* #SSD "Short Stature Disorder"
* #SSL "Skin Sire of Lesions"
* #SSLF "Stress fracture, left foot"
* #SSRF "Stress fracture, right foot"
* #SSS "Segmental & somatic dysfn sacrum or sacr"
* #ST "Sore Tongue"
* #STE "Stress Test Evaluations"
* #STEAR "Skin Tear"
* #STEMI "STEMI"
* #STI "Sexually Transmitted Infections"
* #STR "Strabismus"
* #STROKE "Stroke"
* #STT "Soft Tissue Tumour"
* #SU "Sepsis Urinary"
* #SUC "Suboptimal Control"
* #SUDT "Suicidal Tendencies"
* #SVT "SVT Elevations"
* #SW "Scalp Wound"
* #SWM "Symptoms W Artificial Menopause"
* #SWS "Sturge-Weber Syndrome"
* #SYP "Syphillis"
* #SYS "Systemic Lupus"
* #T01 "T1DM - Support with management"
* #T02 "T1DM, Complex History"
* #T03 "T2DM"
* #T04 "T2DM on Insulin / Declining Renal Functi"
* #T05 "T2DM review on insulin"
* #T06 "T2DM, Diabetes Education"
* #T07 "T2DM/ Recent Hypo"
* #T1420 "Fracture of unspecified body region,clsd"
* #T1421 "Fracture of unspecified body region,open"
* #T1D "Diabetes T1DM"
* #T2D "NIDDM"
* #T784 "Allergy, unspecified"
* #TA "Talipes"
* #TALI "Talipes"
* #TB "TB"
* #TBI "Traumatic Brain Injury"
* #TC "Tongue Cancer"
* #TCA "Tongue Cancer"
* #TCEL "T-Cell Lymphoma / Non Hodgkins"
* #TCM "Trichomonas"
* #TE "Tennis Elbow"
* #TEA "Tear"
* #TERA "Teratoma"
* #TES "Testicular Cancer"
* #TESTI "Testes Inguinal"
* #TESTM "Testes Maldescent"
* #TESTP "Testes Poor Descent"
* #TESTU "Testes Undescended"
* #TETH "Tethered Cord"
* #TF "Trigger Finger"
* #THA "Thalassemia"
* #THY "Thyroidectomy"
* #THYP "Papillary Thyroid Carcinoma"
* #TINN "Tinnitus"
* #TIPH "Tight Phimosis"
* #TIRE "Tiredness"
* #TJP "Temporomandibular Joint Pain/Dysfunction"
* #TM "Thyroid Metastatic"
* #TMJ "TMJ Dysfunction"
* #TOA "Tonsillitis & Adenoiditis"
* #TOL "Tongue Lesion"
* #TON "Tonsillitis"
* #TOO "Torsion Of Ovary"
* #TOP "Termination Of Pregnancy"
* #TOT "Tongue Tie"
* #TPL "Threatened Preterm Labour"
* #TRA "Tracheostomy"
* #TRCHDIS "Tracheal Disorder"
* #TRH "Trauma Rehabilitation"
* #TRI "Trisomy 18"
* #TSCAN "Testicular Cancer"
* #TSCC "Tongue Squamous Cell Carcinoma"
* #TSL "Tarsal tunnel syndrome, left lower limb"
* #TSR "Turners, Silver-Russel"
* #TSY "Turner Syndrome"
* #TT "Tongue Tie"
* #TU0 "Retinoblastoma"
* #TU1 "Optic Nerve Glioma"
* #TU2 "Other Tumours"
* #TUM "Tumour"
* #UAL "Ulcer Anterior Leg"
* #UAP "Upper Abdo Pain"
* #UAT "Arterial Ulcer"
* #UBL "Ulcer Bilateral Legs"
* #UCY "Unsatisfactory Cytology"
* #UDC "Upper Dental Clearance"
* #UDF "Ulcer Diabetic Foot"
* #UF "Urinary Frequency"
* #UH "Urinary Hesitancy"
* #UI "Urge Incontinence"
* #UIN "Uterine Myoma"
* #ULC "Ulcers"
* #ULL "Ulcer Left Leg"
* #ULM "Ulcer Lateral Malleolus"
* #UNSTABLE "Unstable Angina"
* #UOC "Unspecified Ovarian Cysts"
* #UOF "Unsteadiness on feet"
* #UPL "Ulcer Posterior Leg"
* #URI "Urinary Incontinence"
* #URL "Ulcer Right Leg"
* #URR "Urinary Retention"
* #URT "Urticaria"
* #URU "Urinary Urgency"
* #USTRC "Urethral Stricture"
* #UTI "Urinary Tract Infection"
* #UVU "Uvula"
* #UVUL "Uvulectomy"
* #UWL "Unintentional weight loss >10% in 6 mths"
* #UWL2 "Unintentional weight loss <10% in 6 mths"
* #V1 "Vin 1"
* #V2 "Vin 2"
* #VAG "Vaginismus"
* #VAS "Vasculitis"
* #VASC "Vasculitis"
* #VASD "Vascular Dementia"
* #VCP "Vocal Cord Paralysis"
* #VD "Vaginal Dysplasia"
* #VD0 "Amblyopia (non-specific)"
* #VD01 "Anisometropic Amblyopia"
* #VD02 "Ammetropic Amblyopia"
* #VD03 "Strabismic Amblyopia"
* #VD04 "Stimulus Deprivation Amblyopia"
* #VD1 "Monocular Diplopia"
* #VD10 "Neurofibromatosis Type 1"
* #VD11 "Retinal Dystrophy"
* #VD12 "Retinal Detachment"
* #VD13 "ROP"
* #VD2 "Other Visual Disturbances"
* #VD3 "Reduced VA with no reason"
* #VD4 "Colour Vision Defect"
* #VD5 "Delayed Visual Maturation"
* #VD6 "Sig. Visual Impairment (Blind Found Reg)"
* #VD7 "Functional Vision Loss"
* #VD8 "Cerebral Visual Impairment"
* #VD9 "Incomplete Assessment"
* #VEF "Ventricular Failure"
* #VENE "Venesection"
* #VER "Vertigo"
* #VES "Vestublitis"
* #VF "Ventricular Failure"
* #VF0 "Glaucoma"
* #VF1 "Neurological Visual Field Defect"
* #VF2 "Other visual field disorder"
* #VFD "Visual Field Defect"
* #VIN "Venous Insuff,Ulceration,Poor Wound Heal"
* #VIR "Vision Review"
* #VISI "Vision"
* #VNM "Vulvar Neoplasm -Malignant"
* #VNN "Vulvar Neoplasm -Non-Malignant"
* #VOL "Volvulus"
* #VP1 "Homonymous Hemianopia"
* #VP2 "Chiasmal Compression"
* #VP3 "Constriction"
* #VP4 "Central Scotoma"
* #VP5 "Other Visual Pathway Defects"
* #VPRE "Vulnerable Pregnancy"
* #VV "Varicose Veins"
* #WDE "Wound Dehiscence"
* #WEI "Weight Management"
* #WEIG "Weight"
* #WI "Weight Issues"
* #WOM "Womens Health"
* #WPU "Wounds/Pressure Ulcer"
* #WRE "Wound Review"
* #WRI "Wrist Pain"
* #WSIN "Wound Sinus"
* #WTS "Warts"
* #Z133 "Special screening examination for mental"
* #Z369 "Antenatal screening, unspecified"
* #Z609 "Problem related to social environment, u"

*/

// values noted from DT1_WebPAS
* #AMBBP   "Ambulatory BP Machine"
* #CLINIC  "Antenatal Clinic Obstetric"
* #ECV     "External Cephalic Version"
* #GENCARD "General Cardiology"
* #OTH     "Other"
* #PLP     "Planned procedure"

ValueSet: NZCentralRegionReferralReasonValueSet
Id: nzcr-referral-reason-vs
Title: "NZ Central Region - Referral Reason Value Set"
Description:  "Referral Reason codes ex. WebPAS in NZ Central Region."

* ^url = $NZCentralRegionReferralReasonVS
* ^status = #active
* ^experimental = false

* include codes from system nzcr-referral-reason-cs
